#!/bin/bash
set -euo pipefail

# Build the Debian-family package without requiring stdeb or dh-python.
#
# Build requirements:
#   python3 (>= 3.8), python3-setuptools, dpkg-dev
#
# Runtime dependencies are recorded in the generated package control file and
# are resolved by apt when the package is installed.

cd "$(dirname "$0")/.."

package_name="opencobolide"
package_version="4.7.6+modern6"
package_root="build/deb-root"
output_file="dist/${package_name}_${package_version}_all.deb"

rm -rf "$package_root"
mkdir -p "$package_root/DEBIAN"
mkdir -p "$package_root/usr/share/doc/$package_name"
mkdir -p "$package_root/usr/share/man/man1"
mkdir -p dist

python3 setup.py install \
    --root="$(pwd)/$package_root" \
    --install-lib=/usr/lib/python3/dist-packages \
    --install-scripts=/usr/bin \
    --install-data=/usr \
    --single-version-externally-managed \
    --record="$(pwd)/build/deb-install-files.txt"

# Bytecode is generated by Python on the target system when appropriate.
find "$package_root" -type d -name __pycache__ -prune -exec rm -rf {} +
find "$package_root" -type f -name '*.pyc' -delete
find "$package_root" -type f -name '*.pyo' -delete

copyright="$package_root/usr/share/doc/$package_name/copyright"
printf '%s\n' \
    'Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/' \
    'Upstream-Name: OpenCobolIDE' \
    'Source: https://github.com/OpenCobolIDE/OpenCobolIDE' \
    '' \
    'Files: *' \
    'Copyright: 2014-2016 Colin Duquesnoy and OpenCobolIDE contributors' \
    'License: GPL-3+' \
    ' This program is free software: you can redistribute it and/or modify' \
    ' it under the terms of the GNU General Public License as published by' \
    ' the Free Software Foundation, either version 3 of the License, or' \
    ' (at your option) any later version.' \
    ' .' \
    ' On Debian systems, the complete text of the GNU General Public License' \
    ' version 3 can be found in /usr/share/common-licenses/GPL-3.' \
    '' \
    'Files: open_cobol_ide/extlibs/*' \
    'Copyright: respective upstream authors' \
    'License: various' \
    ' Bundled legacy dependencies retain their upstream copyright and license' \
    ' notices in their source files and package metadata.' \
    > "$copyright"

install -m 0644 share/opencobolide.1 \
    "$package_root/usr/share/man/man1/opencobolide.1"
gzip -n -9 "$package_root/usr/share/man/man1/opencobolide.1"

changelog="$package_root/usr/share/doc/$package_name/changelog"
printf '%s\n' \
    "$package_name ($package_version) unstable; urgency=medium" \
    '' \
    '  * Preserve the original OpenCobolIDE authorship and maintainer.' \
    '  * Polish OpenCobolIDE 4.7.6 for modern Python, PyQt5, and Debian Linux.' \
    '  * Fix bundled Pygments regular expressions for Python 3.12.' \
    '  * Remove obsolete release assets and runtime-unneeded bundled tests.' \
    '  * Complete compatibility and packaging work with OpenAI Codex assistance.' \
    '' \
    ' -- OpenCobolIDE compatibility build <noreply@opencobolide.invalid>  Fri, 25 Sep 2026 07:15:00 +0300' \
    > "$changelog"
gzip -n -9 "$changelog"

installed_size="$(du -sk "$package_root/usr" | cut -f1)"
control="$package_root/DEBIAN/control"
printf '%s\n' \
    'Package: opencobolide' \
    "Version: $package_version" \
    'Section: devel' \
    'Priority: optional' \
    'Architecture: all' \
    'Depends: python3 (>= 3.8), python3-pyqt5 (>= 5.15), gnucobol' \
    "Installed-Size: $installed_size" \
    'Maintainer: Colin Duquesnoy <colin.duquesnoy@gmail.com>' \
    'Homepage: https://github.com/OpenCobolIDE/OpenCobolIDE' \
    'Description: COBOL IDE polished for modern Debian Linux' \
    ' This unofficial compatibility package preserves the original project' \
    ' ownership and adds modern Python and PyQt5 compatibility with assistance' \
    ' from OpenAI Codex. It is not a new or official upstream release.' \
    > "$control"

find "$package_root" -type d -exec chmod 0755 {} +
find "$package_root" -type f -exec chmod 0644 {} +
chmod 0755 "$package_root/usr/bin/opencobolide"
chmod 0755 "$package_root/DEBIAN"
dpkg-deb --root-owner-group --build "$package_root" "$output_file"

sha256sum "$output_file"
